project:
  type: website
  output-dir: docs

website:
  title: "Yair Mau"
  search: true
  favicon: archive/site_images/favicon.ico
  navbar:
    logo: archive/site_images/site-logo-light.png
    pinned: false
    collapse: true
    search: true
format:
  html:
    theme:
      - flatly
      - custom.scss
      # - custom-light.scss
      # dark: [darkly, custom.scss, custom-dark.scss]
    css: styles.css
    highlight: false
    # https://quarto.org/docs/output-formats/html-code.html#highlighting
    highlight-style: breezedark
    mainfont: Ubuntu
    monofont: Ubuntu Mono
    max-width: "700"
    include-in-header:
      - includes.html
    




